# Generated by Django 5.1.4 on 2025-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='profilePic',
            field=models.ImageField(default='profile_pics/default.jpg', max_length=255, upload_to='profile_pics/'),
        ),
    ]
